
services:

  postgres:
    image: postgis/postgis:17-3.5
    container_name: solarwind-postgres

    restart: always

    environment:
      POSTGRES_DB: solarwind_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d solarwind_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4

    container_name: solarwind-pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@solarwind.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

volumes:
  postgres_data: