"""allow pre-project sites

Revision ID: 2a4a931a854b
Revises: 053a7ed900f7
Create Date: 2026-08-17 06:32:06.804214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4a931a854b'
down_revision: Union[str, Sequence[str], None] = '053a7ed900f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sites', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('sites_project_id_fkey'), 'sites', type_='foreignkey')
    op.create_foreign_key(None, 'sites', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.create_foreign_key(op.f('sites_project_id_fkey'), 'sites', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sites', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
