"""add deployment history

Revision ID: f6c63786c869
Revises: 2a4a931a854b
Create Date: 2026-08-17 10:25:21.753324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c63786c869'
down_revision: Union[str, Sequence[str], None] = '2a4a931a854b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('technology', sa.String(length=50), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_history_changed_by'), 'deployment_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_deployment_history_id'), 'deployment_history', ['id'], unique=False)
    op.create_index(op.f('ix_deployment_history_project_id'), 'deployment_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployment_history_site_id'), 'deployment_history', ['site_id'], unique=False)
    op.create_index(op.f('ix_deployment_history_status'), 'deployment_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_history_status'), table_name='deployment_history')
    op.drop_index(op.f('ix_deployment_history_site_id'), table_name='deployment_history')
    op.drop_index(op.f('ix_deployment_history_project_id'), table_name='deployment_history')
    op.drop_index(op.f('ix_deployment_history_id'), table_name='deployment_history')
    op.drop_index(op.f('ix_deployment_history_changed_by'), table_name='deployment_history')
    op.drop_table('deployment_history')
    # ### end Alembic commands ###
